### ISSUE TITLE
Use Endb instead as a primary database

### ISSUE THREAD

**Issue by chroventer** [redxtech/devmod#15]
# Title
Use [Endb](https://npmjs.com/package/endb) as your primary database.

# Description
There are tons of advantages of using Endb. It has great features such as:
- Object-oriented & Persistent Storage
- Configurable (you can create multiple SQLite tables, and configure almost everything.)
- Performant, it is 100x faster than normal SQLite3 database wrapper.
- User and beginner-friendly, with the key-value feature like Enmap, it can be pretty easy to switch and it is a great choice.

**Comment by redxtech** [comment]
Submit a PR with how it would look for a few cases and I'll consider it. Based on your description it sounds nice though.

**Comment by chroventer** [comment]
@redxtech, alright, I am currently working on that.

**Comment by chroventer** [comment]
Perhaps, you can take a look at the [documentation for Endb](https://endb.js.org).
- [GitHub Link](https://github.com/chroventer/endb)
